### ISSUE TITLE
[please fix] Block ID problem when you update

### ISSUE THREAD

**Issue by KillerJWB86** [kreezxil/World-of-Dragons#200]
**Describe the bug**
 So when i updated the pack from 202 to 203 alot of the IDs got screwed up

**Screenshots**

**Versions:**

 - Minecraft:
 - Forge:forge-1.12.2-14.23.5.2838
 - Mod Pack :16.2.203
 - Mod Name:
 - Mod Version:

**Logs**

Find out how to get me what I need at [What is a Crash Report](https://github.com/kreezxil/World-of-Dragons/wiki/Crash-Reports)

Latest Log:
https://pastebin.com/Hqgas3za
https://pastebin.com/XR3McEZH

**Additional context**

I have liquid metal all over my base and block of platnum in my walls.Also if you go to line 4277,im sure that has alot to do with my problem.

**Comment by KillerJWB86** [comment]
So i added all the changes you did to 203 one at a time and the bug happend on the last step when i added AW2.I get this error 
[16:18:22] [Server thread/ERROR] [net.minecraft.world.storage.SaveFormatOld]: Exception reading .\world\level.dat
java.lang.RuntimeException: Invalid id 4096 - maximum id range exceeded.
    at net.minecraftforge.registries.ForgeRegistry.add(ForgeRegistry.java:295) ~[modpack_server.jar:?]
    at net.minecraftforge.registries.ForgeRegistry.loadIds(ForgeRegistry.java:695) ~[modpack_server.jar:?]
    at net.minecraftforge.registries.GameData.loadFrozenDataToStagingRegistry(GameData.java:820) ~[modpack_server.jar:?]
    at net.minecraftforge.registries.GameData.lambda$injectSnapshot$25(GameData.java:763) ~[modpack_server.jar:?]
    at com.google.common.collect.HashBiMap.forEach(HashBiMap.java:528) ~[minecraft_server.1.12.2.jar:?]
    at net.minecraftforge.registries.GameData.injectSnapshot(GameData.java:760) ~[GameData.class:?]
    at net.minecraftforge.fml.common.FMLContainer.readData(FMLContainer.java:172) ~[FMLContainer.class:?]
    at farseek.world.storage.package$.readData(package.scala:30) ~[package$.class:?]
    at farseek.world.storage.package.readData(package.scala) ~[package.class:?]
    at net.minecraftforge.fml.common.FMLCommonHandler.handleWorldDataLoad(FMLCommonHandler.java:423) ~[FMLCommonHandler.class:?]
    at net.minecraft.world.storage.SaveFormatOld.loadAndFix(SaveFormatOld.java:119) [bfc.class:?]
    at net.minecraft.world.storage.SaveHandler.loadWorldInfo(SaveHandler.java:122) [bfb.class:?]
    at net.minecraft.server.MinecraftServer.loadAllWorlds(MinecraftServer.java:228) [MinecraftServer.class:?]
    at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:270) [nz.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486) [MinecraftServer.class:?]
    at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]
[16:18:22] [Server thread/WARN] [FML]: Forge Mod Loader detected that the backup level.dat is being used.
 This may happen due to a bug or corruption, continuing can damage
your world beyond repair or lose data / progress.
 It's recommended to create a world backup before continuing.
 Run the command /fml confirm or or /fml cancel to proceed.

and i have to do a FML CONFIRM and when i load into the world all the IDs have been changed.If you want i can upload my server files so you can do better testing if you want.

**Comment by KillerJWB86** [comment]
So i found the problem, [16:18:22] [Server thread/ERROR] [net.minecraft.world.storage.SaveFormatOld]: Exception reading .\world\level.dat
java.lang.RuntimeException: Invalid id 4096 - maximum id range exceeded.
So i added https://minecraft.curseforge.com/projects/notenoughids/files/2695044 and it works fine.The problem now is now everyone that joins the server knows how to add mods themself.Can you PLZ add this to your update so i can update my servers.
