### ISSUE TITLE
[Help' Can't connect to server 

### ISSUE THREAD

**Issue by Oghoob** [kreezxil/World-of-Dragons#54]
**Describe the bug**
I  followed the instructions in order to create my own server using the video that was provided, but when i run the server, i get an error message and when i try to join the server I get the message io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection Refused: no further information:
The error message i get in the server console is:
[18:28:43] [Server thread/ERROR] [JavaPatcher]: Error patching net.minecraft.network.play.server.SPacketCustomPayload with addMethod
java.lang.RuntimeException: cannot find net.minecraft.network.play.server.SPacketCustomPayload: iw found in net/minecraft/network/play/server/SPacketCustomPayload.class
        at javassist.CtClassType.getClassFile3(CtClassType.java:208) ~[CtClassType.class:?]
        at javassist.CtClassType.getClassFile2(CtClassType.java:173) ~[CtClassType.class:?]
        at javassist.compiler.Javac.<init>(Javac.java:53) ~[javassist-3.22.0-CR1.jar:?]
        at javassist.CtNewMethod.make(CtNewMethod.java:69) ~[javassist-3.22.0-CR1.jar:?]
        at javassist.CtNewMethod.make(CtNewMethod.java:45) ~[javassist-3.22.0-CR1.jar:?]
        at me.nallar.javapatcher.patcher.Patches.addMethod(Patches.java:106) ~[Patches.class:1.8+Jenkins-b61.git-8893876c05313e7818055c79e31cf8e828c877a2]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_191]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_191]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_191]
        at me.nallar.javapatcher.patcher.Patcher$PatchMethodDescriptor.run(Patcher.java:399) [Patcher$PatchMethodDescriptor.class:1.8+Jenkins-b61.git-8893876c05313e7818055c79e31cf8e828c877a2]
        at me.nallar.javapatcher.patcher.Patcher$PatchMethodDescriptor.run(Patcher.java:364) [Patcher$PatchMethodDescriptor.class:1.8+Jenkins-b61.git-8893876c05313e7818055c79e31cf8e828c877a2]
        at me.nallar.javapatcher.patcher.Patcher$ClassPatchDescriptor.runPatches(Patcher.java:514) [Patcher$ClassPatchDescriptor.class:1.8+Jenkins-b61.git-8893876c05313e7818055c79e31cf8e828c877a2]
        at me.nallar.javapatcher.patcher.Patcher.patch(Patcher.java:211) [Patcher.class:1.8+Jenkins-b61.git-8893876c05313e7818055c79e31cf8e828c877a2]
        at org.minimallycorrect.modpatcher.api.ModPatcherTransformer$ClassTransformer.transform(ModPatcherTransformer.java:154) [ModPatcher-1.12-SNAPSHOT.jar:1.12-SNAPSHOT+Jenkins-b5.git-24e3b38023c281ee5d327595ecaea7f37f198dfc]
        at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) [launchwrapper-1.12.jar:?]
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) [launchwrapper-1.12.jar:?]
        at java.lang.ClassLoader.loadClass(Unknown Source) [?:1.8.0_191]
        at java.lang.ClassLoader.loadClass(Unknown Source) [?:1.8.0_191]
        at net.minecraftforge.fml.common.network.FMLOutboundHandler.write(FMLOutboundHandler.java:354) [FMLOutboundHandler.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) [minecraft_server.1.12.2.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730) [minecraft_server.1.12.2.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816) [minecraft_server.1.12.2.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723) [minecraft_server.1.12.2.jar:?]
        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:111) [minecraft_server.1.12.2.jar:?]
        at io.netty.handler.codec.MessageToMessageCodec.write(MessageToMessageCodec.java:116) [minecraft_server.1.12.2.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) [minecraft_server.1.12.2.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801) [minecraft_server.1.12.2.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814) [minecraft_server.1.12.2.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794) [minecraft_server.1.12.2.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831) [minecraft_server.1.12.2.jar:?]
        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1032) [minecraft_server.1.12.2.jar:?]
        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:296) [minecraft_server.1.12.2.jar:?]
        at net.minecraftforge.fml.common.network.simpleimpl.SimpleNetworkWrapper.sendToAll(SimpleNetworkWrapper.java:236) [SimpleNetworkWrapper.class:?]
        at sereneseasons.handler.season.SeasonHandler.sendSeasonUpdate(SeasonHandler.java:132) [SeasonHandler.class:?]
        at sereneseasons.handler.season.SeasonHandler.onWorldTick(SeasonHandler.java:53) [SeasonHandler.class:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_920_SeasonHandler_onWorldTick_WorldTickEvent.invoke(.dynamic) [?:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) [ASMEventHandler.class:?]
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) [EventBus.class:?]
        at net.minecraftforge.fml.common.FMLCommonHandler.onPostWorldTick(FMLCommonHandler.java:274) [FMLCommonHandler.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:776) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_191]

**To Reproduce**
1. Install the server
2. Run the server
3.Wait for server to finish starting
**Screenshots**
![screenshot 2](https://user-images.githubusercontent.com/47310317/52188752-619c3080-27e9-11e9-9d85-dd303cf7b027.png)

**Versions:**

 - Minecraft:1.12
 - Forge:
 - Mod Pack 14.17.149
 - Mod Name:
 - Mod Version:

**Additional context**
I don't really know what else to add

**Comment by kreezxil** [comment]
# Congratulations
You followed all the instructions!

# My Bad
I shipped a server.properties file that set the default port to 25765.

## Three Ways to Resolve
1. Change the server entry you made for it to be <ip>:25765
1. Edit the server.properties file and change the port values back to 25565
1. **- OR -** delete the server.properties file and let it regenerate.

### What I would do
I would use option 2 above and change the values of the port fields and then restart the server.
